### ISSUE TITLE
 Meteor Forums question

### ISSUE THREAD

**Issue by smooJitter** [tomitrescak/apollo-modules#2]
https://forums.meteor.com/t/tips-on-modular-micro-serviceified-graphql-server/29257/7?u=jitterbop

**Comment by tomitrescak** [comment]
@smooJitter  that schema just generates an Input/Output schema type.
That is if you need your schema type to flow from both ends. Your example in the final schema would lead to:

type Exercise {
    _id: String
    name: String
    instructions: String
    group: String
    questions: [Question]
  }

input ExerciseInput {
    _id: String
    name: String
    instructions: String
    group: String
    questions: [QuestionInput]
  }

Not much magic :wink: Just keep the definition shorter and less prone for errors when you change type or input.

**Comment by smooJitter** [comment]
I thought so.  I was basically trying inject your work into the conversation. Thank you.
